name: QRange
description: Qrange is a web app which create QR for image and pdf.
publish_to: 'none' 
version: 3.0.2+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text_pk: ^3.0.0
  barcode_scan2: ^4.1.4
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  device_preview: ^0.7.4
  dotted_border: ^2.0.0+1
  file_picker: ^3.0.3
  firebase_storage: ^10.0.1
  flutter:
    sdk: flutter
  flutter_dropzone: ^2.0.1
  flutter_screenutil: ^5.0.0+2
  hexcolor: ^2.0.4
  images_picker: ^1.2.4
  path_provider: ^2.0.2
  permission_handler: ^8.1.1
  printing: ^5.5.0
  qr_flutter: ^4.0.0
  scan: ^1.4.3
  screenshot: ^1.2.1
  scroll_snap_list: ^0.8.2
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_pdfviewer: ^19.2.49-beta
  # top_snackbar_flutter: ^1.0.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.9
  url_strategy: ^0.2.0
  uuid: ^3.0.4
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    # - assets/images/logo2.png
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/font/Raleway-Black.ttf
        - asset: assets/font/Raleway-Light.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

